rvm:
  - 1.9.2

env: "RAILS_ENV='test'"

script: "bundle exec rspec --tag ~javascript spec/"

before_script:
  - "cp config/database.yml.travis config/database.yml"
  - "rake db:create"
  - "rake db:schema:load"

notifications:
  recipients:
    - rmanhaes@gmail.com

branches:
  only:
    - master

